### ISSUE TITLE
😥 I should change that `README` as soon as Possible! 

### ISSUE THREAD

**Issue by brian-ikiara** [brian-ikiara/brian-ikiara.github.io#1]
## :x: That `README`'s got to go!
We know that boilerplate code is necessary, but it is embarrassing if we leave it unmodified. We need to fix this as soon as possible!

## 😡 Change your Commit style!
If you're having a hard time choosing between emojis and a `[[<commit_description>]]`, I'd suggest that you stick to one. It's weird to use both in the same Commit title. Moreover, find a better emoji to represent an `[[Update]]`, as the ✔️ will be awkward if you experience a merge conflict!

**Comment by brian-ikiara** [comment]
## 👋🏾 Hello there
Building this Portfolio will take some time, though not perfect. We're building something presentable. I'll take you up on that suggestion of choosing between an emoji or the `[[<commit_desc>]]`, and I feel that the emojis jive with my personality.

## 🥇 Newer Commits! 
Here's the updated format of our Commit Titles and Descriptions:

```
<emoji> <title>

<Description>
```

To see this in action for an `[[Initial]]` Github Action, this syntax can be as follows:
 
> 🌱 This is my first Commit on this repo

> We're expounding on what is included in this Commit over here.
Another line describing some more stuff!
Even another one...Can you see where I'm going with this?😅 

## :fire: Let's go! Emojis!
 Here's a list of the emojis we'll be using:

| Action | Respective Emoji | What it actually means |
| :---: | :---: | :---: |
| `[[Update]]` | :recycle: | Update existing code or dependencies |
| `[[Test]]` | :test_tube: | Add or modify tests |
| `[[Feature]]` | :sparkles: | Introduce a new feature |
| `[[Setup]]` | :gear: | Set up initial configuration |
| `[[initial]]` | :seedling: | Initial commit or starting point |
| `[[Minor]]` | :bookmark: | Make minor changes or improvements |
| `[[Refactor]]` | :art: | Restructure or clean up code without adding new features |
| `[[Final]]` | :tada: | Finalize or complete a task or project |
| `[[Deletion]]` | :x: | Remove code or files |
| `[[Bugfix]]` | :space_invader: | Fix a bug or resolve an issue |
| `[[Documentation]]` | :books: | Update documentation |
| `[[Deploy]]` | :rocket: | Deploy code to a server or platform |
| `[[Build]]` | :hammer: | Run a build process |
| `[[Review]]` | :mag: | Conduct code review |
| `[[Security]]` | :lock: | Address security concerns or vulnerabilities |
| `[[Optimization]]` | :zap: | Optimize code or improve performance |
| `[[Release]]` | :package: | Release a new version or update |

## :star: New hope?
Seeing that we've resolved your issue, I know this can be a better framework to base my Commits, and I'll fix the documentation as soon as possible! Look out for the following Commit alongside the `README`:

> :books: Revamped `README` and made it more descriptive

> ...more details here...

With all that said...cheers?🍻

**Comment by brian-ikiara** [comment]
## 🙌🏾 Interesting development...
I realized that the Commit messages could be more descriptive by including a `[<context> || <file> || <directory>]` Tag after the `[[<commit_desc>]]`. Though the choice of emojis may be exquisite, more info could be obtained per Commit through this new Tag.[^1] Cheerio :beers:

***For Example:***
> :art: [render.py] Modularized `BatchRenderer` ...

**Comment by suna-proctor** [comment]
## :alien: Emojis are back with the sauce!

I got sick of all the bool and lack of personality on my Commits so I literally said, "Fuck it!"

Who the F cares?
